# Generated by Django 5.0.7 on 2024-12-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfNotif', models.CharField(max_length=80)),
                ('notifFrom', models.CharField(max_length=80)),
                ('notifTo', models.CharField(max_length=80)),
                ('groupName', models.CharField(default='', max_length=10)),
                ('sender', models.CharField(default='', max_length=8)),
            ],
        ),
    ]
