# Generated by Django 3.2.12 on 2024-12-31 12:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=50)),
                ('picture', models.ImageField(default='undefined.jpg', upload_to='')),
                ('owner', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('is_muted', models.BooleanField(default=False)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('mute_always', models.BooleanField(default=False)),
                ('groupNameUser', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user_online',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_online', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='userBlockChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_block', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='private_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('is_block', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('online', models.IntegerField(default=0)),
                ('user_block', models.ManyToManyField(blank=True, to='chat.userBlockChat')),
                ('user_online', models.ManyToManyField(blank=True, to='chat.user_online')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=10, unique=True)),
                ('typeOfGroup', models.CharField(default='', max_length=50)),
                ('code', models.TextField(default='', null=True)),
                ('users', models.ManyToManyField(blank=True, related_name='users', to='chat.GroupUsers')),
                ('users_baned', models.ManyToManyField(blank=True, to='chat.GroupUsers')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=60)),
                ('sender_username', models.CharField(default='', max_length=60)),
                ('message', models.CharField(max_length=1000)),
                ('create', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.groups')),
            ],
            options={
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='chat_mesg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default=None, max_length=300)),
                ('vu', models.BooleanField(default=False)),
                ('message', models.CharField(default=None, max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chaaat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.private_chat')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
